name: btree
description: An in-memory B-Tree implementation
version: 0.2.0
homepage: https://github.com/kseo/btree

environment:
  sdk: '^2.0.0'

dependencies:
  quiver: '^3.0.0'
  tuple: '^2.0.0'

dev_dependencies:
  lints: ^1.0.1
  test: '^1.20.0'
